INSERT into CARMODEL(MODEL_ID,MODEL_TY,COLOR)
VALUES(CARMODEL_seq.NEXTVAL,'BERLINGO','BLACK');

INSERT into CARMODEL(MODEL_ID,MODEL_TY,COLOR)
VALUES(CARMODEL_seq.NEXTVAL,'CLUBMAN','GREEN');

INSERT into CARMODEL(MODEL_ID,MODEL_TY,COLOR)
VALUES(CARMODEL_seq.NEXTVAL,'ASX','BROWN');

INSERT into CARMODEL(MODEL_ID,MODEL_TY,COLOR)
VALUES(CARMODEL_seq.NEXTVAL,'MGF','NAVY');

INSERT into CARMODEL(MODEL_ID,MODEL_TY,COLOR)
VALUES(CARMODEL_seq.NEXTVAL,'944','ULTRA BLUE');

INSERT into CARMODEL(MODEL_ID,MODEL_TY,COLOR)
VALUES(CARMODEL_seq.NEXTVAL,'KORANDO','WHITE');

INSERT into CARMODEL(MODEL_ID,MODEL_TY,COLOR)
VALUES(CARMODEL_seq.NEXTVAL,'AURIS','BLACK');

INSERT into CARMODEL(MODEL_ID,MODEL_TY,COLOR)
VALUES(CARMODEL_seq.NEXTVAL,'CADDY','RED');

INSERT into CARMODEL(MODEL_ID,MODEL_TY,COLOR)
VALUES(CARMODEL_seq.NEXTVAL,'F-PACE','MAROON');

INSERT into CARMODEL(MODEL_ID,MODEL_TY,COLOR)
VALUES(CARMODEL_seq.NEXTVAL,'MODELS','GREEN');

INSERT into CARMODEL(MODEL_ID,MODEL_TY,COLOR)
VALUES(CARMODEL_seq.NEXTVAL,'CAPTIVA','ORANGE');