INSERT into CARRENT(RENT_ID,CARCUST_ID,RENT_DATE,RETURN_DATE)
VALUES(CARRENT_SEQ.NEXTVAL,104,'10-AUG-07','16-AUG-07')

INSERT into CARRENT(RENT_ID,CARCUST_ID,RENT_DATE,RETURN_DATE)
VALUES(CARRENT_SEQ.NEXTVAL,105,'01-SEP-07','05-SEP-07')

INSERT into CARRENT(RENT_ID,CARCUST_ID,RENT_DATE,RETURN_DATE)
VALUES(CARRENT_SEQ.NEXTVAL,106,'06-JUL-07','12-JUL-07')

INSERT into CARRENT(RENT_ID,CARCUST_ID,RENT_DATE,RETURN_DATE)
VALUES(CARRENT_SEQ.NEXTVAL,107,'15-JUN-07','20-JUN-07')

INSERT into CARRENT(RENT_ID,CARCUST_ID,RENT_DATE,RETURN_DATE)
VALUES(CARRENT_SEQ.NEXTVAL,122,'14-JUL-07','20-JUL-07')

INSERT into CARRENT(RENT_ID,CARCUST_ID,RENT_DATE,RETURN_DATE)
VALUES(CARRENT_SEQ.NEXTVAL,123, '13-SEP-07','19-SEP-07')

INSERT into CARRENT(RENT_ID,CARCUST_ID,RENT_DATE,RETURN_DATE)
VALUES(CARRENT_SEQ.NEXTVAL,128,'02-MAR-07','11-MAR-07')

INSERT into CARRENT(RENT_ID,CARCUST_ID,RENT_DATE,RETURN_DATE)
VALUES(CARRENT_SEQ.NEXTVAL,129,'04-MAY-07','12-MAY-07')

INSERT into CARRENT(RENT_ID,CARCUST_ID,RENT_DATE,RETURN_DATE)
VALUES(CARRENT_SEQ.NEXTVAL,130,'10-APR-07','19-APR-07')

INSERT into CARRENT(RENT_ID,CARCUST_ID,RENT_DATE,RETURN_DATE)
VALUES(CARRENT_SEQ.NEXTVAL,131,'12-MAY-07','20-MAY-07')









