------CREATING A STORE PROCEDURE ON HOW TO GET A CAR_TYPE BASED ON THE MODEL_ID
CREATE OR REPLACE PROCEDURE GET_CAR_TYPE 
(
----input value----
  MODE_ID_INPUT IN NUMBER 
, MODEL_TYPE_OUTPUT OUT VARCHAR2 
) AS 
------output value----
BEGIN
 SELECT MODEL_TYPE INTO MODEL_TYPE_OUTPUT FROM CARMODEL WHERE MODEL_ID =MODE_ID_INPUT;
END GET_CAR_TYPE;