set SERVEROUTPUT ON;
DECLARE
  CARNO CARRENT.RENT_ID%TYPE;
  CARET CARRENT.RENT_DATE%TYPE;
  CURSOR CAR_CURSOR IS SELECT RENT_ID,RENT_DATE FROM CARRENT;
BEGIN
   OPEN CAR_CURSOR;
   LOOP
       FETCH CAR_CURSOR INTO CARNO,CARET;
       EXIT WHEN CAR_CURSOR%ROWCOUNT >20 OR CAR_CURSOR%NOTFOUND;
       
    DBMS_OUTPUT.PUT_LINE(TO_CHAR(CARNO)||' '|| CARET);
     END LOOP;
     close CAR_CURSOR;
END;