SET SERVEROUTPUT ON;

------Delete a Customer 
CREATE OR REPLACE PROCEDURE DEL_CARCUST( P_CARCUST_ID IN OUT CARCUST.CARCUST_ID%TYPE,
                                         P_ERROR_MSG OUT VARCHAR2)
IS

BEGIN
    DELETE FROM CARCUST WHERE CARCUST_ID =P_CARCUST_ID;
    
    IF SQL%ROWCOUNT=0 THEN
       RAISE_APPLICATION_ERROR(-20001,'  THIS '' CUSTOMER '|| P_CARCUST_ID ||' DOES NOT EXIST ');
        
       
       
    END IF;
    
    COMMIT;
EXCEPTION
   WHEN OTHERS THEN
     P_ERROR_MSG := SQLERRM;
END;
------------INVOKING THIS PROCESDURE 
DECLARE
V_ERROR_MGS  VARCHAR2(4000);
V_CARCUST_ID number:=133;
BEGIN
  DEL_CARCUST(V_CARCUST_ID,V_ERROR_MGS);
   DBMS_OUTPUT.PUT_LINE(V_ERROR_MGS);
END;
--------DELETING THE CUSTOMER ID
------IS JUST PUT A CARCUST_ID THE EXIST THEN IT WILL DELETE THE DATA 
