SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION CHECK_ID (CARCUST_ID NUMBER)
RETURN NUMBER 
AS
BEGIN 
  IF CARCUST_ID < 100 THEN
      RETURN 1;
    ELSE
      RETURN 0;
END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN -1;
      WHEN OTHERS THEN 
        RETURN NULL;
END CHECK_ID;
----TESTING THE FUNCTION 
DECLARE
 V_fun_op Number;
BEGIN
   V_fun_op:=CHECK_ID(101);
DBMS_OUTPUT.put_line(V_fun_op);
END;
     

     