----Adding values the CARCUST TABLE 

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(111,'Cinda','WHITMER','An Comhchoiste 7 Merrion','D12B362',6398400,'BEBRAD');


INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(112,'ANTO','TOGGER','Comhluadar 4 Leinster','D1CA6R7',012885894,'ANTOT');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(113,'VESTA','VARNO','Cumann na 7 bhFiann','D14R9C7',012808091,'VESVA');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(114,'RUFINA','FAUNCE','Dáil Bia 47 KILDARE','DE2WL89',016706087,'RUFFAUN');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(115,'RUFINA','FAUNCE','Dáil Bia 47 KILDARE','D12NC89',016706087,'RUFFAUN');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(116,'SHAN','SHATZER','Foras na Gaeilge 7 merrion','DO4TE63',014744446,'SHANSHA');


INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(117,'MINA','SUMNER','TRID 3 DAWSON ST','DL1HF47',087343568,'MINSUNME');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(118,'EXIE','SISE','7 Merrion Sq','D11F2Q0',086942011,'EXISISE');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(119,'MARY','ESAT','The Castle Inn ','D02E863',083780011,'MARESAT');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(120,'MINA','STHAM','19 Br. na Faiche','D96YC60',086906387,'MINST');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(121,'BEN','SMITH','43 East Essex St','D01E4K9',087788008,'BENSMI');

-------CREATING 10 OTHER ROW
INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(111,'JADE','BRATE','20 Main Street,  Citwest','D01E4K9',011398490,'JADBRA');


INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(112,'MIG','MOBLEY',' 4 Belgard road','D96YC60',017088894,'MIMOB');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(113,'LOVIE','TORBETT','7 GOATSTOWN ROAD','D02E863',013908091,'LOVTOR');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(114,'STANTON','WEST','1 Belcount Bray','D02WC89',014006087,'STAWE');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(115,'FAV','KUDER','45 Johnstown Clonee','D11WC09',012306077,'FAKUD');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(116,'LEIS','PINK', '7 Merrion square ','D85CE63',015244446,'LEPINN');


INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(117,'CATH','AIIENN','1 South Bank,Cross','D52HL97',087973560,'CAIIE');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(118,'EULAH','BRINT','10 Merrion North','D02W2P0',084594011,'EUIBRI');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(119,'DARRE','SAUM','11 Sundrive height ','D91E763',085120011,'DARESU');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(120,'LORNA','KETTNER','19 kingswood rd','DC6PC60',0879016382,'LOKETT');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(121,'Rubin','HOADLEY','67 South circular','D99K4W9',086988008,'RUHODI');

------TEN MORE TABLES



INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(111,'RAMONITA','MARSON','An Comhchoiste 7 Merrion','D12B362',6398400,'BEBRAD');


INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(112,'SHELLY','KINTZ','Comhluadar 4 Leinster','D1CA6R7',012885894,'ANTOT');
----NEW TAB
INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(122,'DIAMOND','MELANS','29 Coulson Avenue','D06 TC96',0867328301,'DIMELA');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(123,'BEVERLY','COFFEY','54 Prospect Meadows','T23KH68',0875645310,'BECOFFE');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(124,'MAYA','SANDER','3 Hill Drive,Dublin','D18A262',0895451679,'MASAND');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(125,'CHUN','CARNEGIE','45 Hill Drive','K34X735',0857434120,'CHCARNE');


INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(126,'HULD','MAYH','2 Cois Ealla','D09YX95',0896497236,'HUMAY');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(127,'CAMILL','RAYNE','36 Sandyford','D18 P3K2',0875631356,'CARAYN');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(128,'TONITA','JANAS',' 121 Temple Gardens','D16X2H3',086451209,'TONJAN');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(129,'KENIA','FLECHA','165b Foxrock','D06TC96',087097123,'KEFLEC');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(130,'AUDRIA','COLETTI','41 Kellys Bay Cliffs','DT08G90',085096780,'AUCLET');

-------CREATING 10 OTHER ROW
INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(111,'JADE','BRATE','20 Main Street,  Citwest','D01E4K9',011398490,'JADBRA');


INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(112,'MIG','MOBLEY',' 4 Belgard road','D96YC60',017088894,'MIMOB');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(113,'LOVIE','TORBETT','7 GOATSTOWN ROAD','D02E863',013908091,'LOVTOR');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(114,'STANTON','WEST','1 Belcount Bray','D02WC89',014006087,'STAWE');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(115,'FAV','KUDER','45 Johnstown Clonee','D11WC09',012306077,'FAKUD');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(116,'LEIS','PINK', '7 Merrion square ','D85CE63',015244446,'LEPINN');


INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(117,'CATH','AIIENN','1 South Bank,Cross','D52HL97',087973560,'CAIIE');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(118,'EULAH','BRINT','10 Merrion North','D02W2P0',084594011,'EUIBRI');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(119,'DARRE','SAUM','11 Sundrive height ','D91E763',085120011,'DARESU');

INSERT into CARCUST(CARCUST_ID,LAST_NAME,FIRST_NAME,ADDRESS,POSTAL_CODE,TEL_PHONE,EMAIL_ADDRESS)
VALUES(120,'LORNA','KETTNER','19 kingswood rd','DC6PC60',0879016382,'LOKETT');
 




