----CREATE A TRIGGER ON CARMO TO DATE,TIME , OLD VALUE, AND NEW VALUE.----
SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER CARMO 
AFTER UPDATE OF CAR_COLOR,CAR_TYPE,CAR_YEAR,MODEL_ID,MODEL_TYPE,RENT_ID ON CARMODEL 
REFERENCING OLD AS old_values NEW AS new_values
FOR EACH ROW 
ENABLE
DECLARE  
V_USER VARCHAR2(20);
V_DATE VARCHAR2(20);
BEGIN
  SELECT USER, TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS')INTO V_USER,V_DATE FROM DUAL;
IF UPDATING THEN
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT ||' ROW HAS BEEN UPDATED BY'||V_USER ||' ON '||V_DATE);
    DBMS_OUTPUT.PUT_LINE('PREVIOUS VALUES :'||' '||:old_values.MODEL_ID||' '||:Old_values.MODEL_TYPE||' '
    ||:old_values.CAR_COLOR||' '||:old_values.CAR_TYPE||' '||:old_values.CAR_YEAR||' '||:old_values.RENT_ID);
    DBMS_OUTPUT.PUT_LINE('UPDATED VALUES :'||' '||:new_values.MODEL_ID||' '||:new_values.MODEL_TYPE||' '
    ||:new_values.CAR_COLOR||' '||:new_values.CAR_TYPE||' '||:new_values.CAR_YEAR||' '||:new_values.RENT_ID);
END IF;
EXCEPTION
WHEN OTHERS THEN
   RAISE_APPLICATION_ERROR(-20001, 'An error was encountered-'||SQLCODE||'-ERROR-'||SQLERRM);
END;