---- ADDING NULL VALUE TO THE EMAIL_ADDRESS
UPDATE CARCUST 
SET EMAIL_ADDRESS = NULL
WHERE CARCUST_ID = 121


UPDATE CARCUST 
SET EMAIL_ADDRESS = NULL
WHERE CARCUST_ID = 115


UPDATE CARCUST 
SET EMAIL_ADDRESS = NULL
WHERE CARCUST_ID = 110


UPDATE CARCUST 
SET EMAIL_ADDRESS = NULL
WHERE CARCUST_ID = 129


